### ISSUE TITLE
Auto-doco doesn't like backslashes

### ISSUE THREAD

**Issue by DrHyde** [DrHyde/perl-modules-Params-Validate-Dependencies#6]
Params with literal \ in will probably fail in Mysterious Ways.

A patch would need to touch both the 'exclusively' function and '_doc_me'.

**Comment by jjatria** [comment]
I was going to give this issue a stab, but I'm not sure if I understand what the problem is?

I tried

```
$ perl -Ilib -E 'use Params::Validate::Dependencies qw( :all ); say Params::Validate::Dependencies::document(exclusively(any_of(qw( \foo foo\ fo\o f\oo \ \\\\ \\\\\\ ))))'
exclusively (any of ('\foo', 'foo\', 'fo\o', 'f\oo', '\', '\\' or '\\\'))
```
and

```
$ perl -Ilib -E 'use Params::Validate::Dependencies qw( :all ); say Params::Validate::Dependencies::document(all_of(qw( \foo foo\ fo\o f\oo \ \\\\ \\\\\\ )))'
all of ('\foo', 'foo\', 'fo\o', 'f\oo', '\', '\\' and '\\\')
```

Is this not the behaviour that is expected?

**Comment by DrHyde** [comment]
Would this be a CPAN Pull Request Challenge thing? :-)

It's possible that I was wrong when I raised the issue, or that I've accidentally fixed it without noticing. In that case I'll close the ticket once I've got tests to prove that it works.

**Comment by jjatria** [comment]
Indeed! I got this module for this month's PRC and I thought I'd take a look at existing issues.

I've sent a couple of pull requests for the other issues, that I imagine you've seen already. If there's anything else that you'd like done on this distribution and could use the extra cycles, let me know!

**Comment by DrHyde** [comment]
I turned your exploratory code above into a test in commit 7a7f9b4a. This proves that the problem does not in fact exist, so closing the ticket. Thanks!

**Comment by jjatria** [comment]
Glad to help!
